# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10qq6qsXSBSj5do_h3jXuRDUjj0IfO1P7
"""

def failure_function(b):
    n = len(b)
    f = [0] * (n + 1)
    t = 0
    f[1] = 0

    for s in range(1, n):
        while t > 0 and b[s] != b[t]:
            t = f[t]
        if b[s] == b[t]:
            t = t + 1
            f[s + 1] = t
        else:
            f[s + 1] = 0

    return f


def kmp(a, b):
    m = len(a)
    n = len(b)
    f = failure_function(b)

    s = 0
    for i in range(m):
        while s > 0 and a[i] != b[s]:
            s = f[s]
        if a[i] == b[s]:
            s = s + 1
        if s == n:
            return "yes"

    return "no"


keyword = "ababaa"
print("Keyword:", keyword)
print("Failure function:", [failure_function(keyword)[s] for s in range(1, len(keyword) + 1)])

print("\nExercise 3.4.6:")

print("\na) text = abababaab")
print("   Result:", kmp("abababaab", keyword))

print("\nb) text = abababbaa")
print("   Result:", kmp("abababbaa", keyword))

print()
text = input("Enter a text string (or press Enter to exit): ").strip()
if text:
    kw = input("Enter the keyword to search: ").strip()
    if kw:
        print("Result:", kmp(text, kw))